cession_project/urls.py
from django.contrib import admin
from django.urls import include, path
from cessions import views
from django_filters.views import FilterView
from cessions.models import Apartment
from cessions.forms import ApartmentFilter

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

                  path("select2/", include("django_select2.urls")),
                  path('', views.cover_view),

                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),

                  # path(),

                  # accounts/login/ [name='login']
                  # accounts/logout/ [name='logout']
                  # accounts/password_change/ [name='password_change']
                  # accounts/password_change/done/ [name='password_change_done']
                  # accounts/password_reset/ [name='password_reset']
                  # accounts/password_reset/done/ [name='password_reset_done']
                  # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
                  # accounts/reset/done/ [name='password_reset_complete']

                  # справочные данные по застройщикам
                  path('developers', views.developers_view, name='developers'),
                  path('add_developer', views.CreateDeveloperView.as_view(), name='create_developer'),
                  path('edit_developer/<slug:pk>', views.EditDeveloperView.as_view(), name='edit_developer'),
                  path('delete_developer/<slug:pk>', views.DeleteDeveloperView.as_view(), name='delete_developer'),

                  # Жилые комплексы
                  path('residential_complexes', views.residential_complex_view, name='residential_complexes_list'),
                  path('add_residential_complex', views.CreateResidentialComplexView.as_view(), name='create_rc'),
                  path(r'edit_residential_complex/<slug:pk>', views.EditResidentialComplexView.as_view(),
                       name='edit_rc'),
                  path('delete_residential_complex/<slug:pk>', views.DeleteResidentialComplexView.as_view(),
                       name='delete_rc'),

                  # особенности (для тегирования квартир)
                  path('features', views.features_view, name='features'),
                  path('create_feature', views.CreateFeatureView.as_view(), name='create_feature'),
                  path('edit_feature/<slug:pk>', views.EditFeatureView.as_view(), name='edit_feature'),
                  path('delete_feature/<slug:pk>', views.DeleteFeatureView.as_view(), name='delete_feature'),

                  # банки (для обременения)
                  path('banks', views.banks_view, name='banks'),
                  path('add_bank', views.CreateBankView.as_view(), name='create_bank'),
                  path('edit_bank/<slug:pk>', views.EditBankView.as_view(), name='edit_bank'),
                  path('delete_bank/<slug:pk>', views.DeleteBankView.as_view(), name='delete_bank'),

                  # просмотр и ввод данных по квартирам
                  # path('apartments', views.apartment_view, name='apartments'),
                  path('apartments', views.ApartmentsListView.as_view(), name='apartments'),
                  # path('apartments', views.apartment_view, name='apartments'),
                  path('add_apartment', views.CreateApartmentView.as_view(), name='create_apartment'),
                  path('apartment_info/<slug:pk>', views.ApartmentInfoView.as_view(), name='apartment_info'),
                  path('apartment_columns', views.ApartmentsColumnVisibility.as_view(), name='apartment_columns'),
                  # path('apartment_filter', views.Filter.as_view(), name='apartment_filter'),
                  path('edit_apartment/<slug:pk>', views.EditApartmentView.as_view(), name='edit_apartment'),
                  path('delete_apartment/<slug:pk>', views.DeleteApartmentView.as_view(), name='delete_apartment'),

                  # заполнение данных по продавцам/покупателям
                  path('persons', views.person_view, name='persons'),
                  path('add_person', views.CreatePersonView.as_view(), name='create_person'),
                  path('edit_person/<slug:pk>', views.EditPersonView.as_view(), name='edit_person'),
                  path('delete_person/<slug:pk>', views.DeletePersonView.as_view(), name='delete_person'),

                  path("select2/", include("django_select2.urls")),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cessions/forms.py
from functools import partial

from django import forms
import django_filters

from .models import Developer, ResidentialComplex, Feature, Apartment, Bank, Person
from bootstrap_modal_forms.forms import BSModalModelForm
import django_select2.forms as select2forms
from django.forms import Select as Select2


class DeveloperWidget(select2forms.ModelSelect2Widget):
    search_fields = [
        "developer__icontains",
    ]


class ApartmentFilter(django_filters.FilterSet):
    id = django_filters.NumberFilter(field_name='id', lookup_expr='icontains')
    commission__gt = django_filters.NumberFilter(field_name='commission', lookup_expr='gt')
    commission__lt = django_filters.NumberFilter(field_name='commission', lookup_expr='lt')
    developer = django_filters.ModelChoiceFilter(queryset=Developer.objects.all())
    residential_complex = django_filters.ModelChoiceFilter(queryset=ResidentialComplex.objects.all())
    queue = django_filters.NumberFilter(field_name='queue_number', lookup_expr='iexact')
    corpus = django_filters.NumberFilter(field_name='corpus', lookup_expr='iexact')
    section = django_filters.NumberFilter(field_name='section', lookup_expr='iexact')
    floor = django_filters.NumberFilter()
    floor__gt = django_filters.NumberFilter(field_name='floor', lookup_expr='gt')
    floor__lt = django_filters.NumberFilter(field_name='floor', lookup_expr='lt')
    floor_overall = django_filters.NumberFilter()
    floor_overall__gt = django_filters.NumberFilter(field_name='floor_overall', lookup_expr='gt')
    floor_overall__lt = django_filters.NumberFilter(field_name='floor_overall', lookup_expr='lt')
    deadline = django_filters.DateFilter(field_name='deadline')
    deadline__gt = django_filters.DateFilter(field_name='deadline', lookup_expr='gt')
    deadline__lt = django_filters.DateFilter(field_name='deadline', lookup_expr='lt')
    number_of_rooms = django_filters.NumberFilter()
    number_of_rooms__gt = django_filters.NumberFilter(field_name="number_of_rooms", lookup_expr="gt")
    number_of_rooms__lt = django_filters.NumberFilter(field_name="number_of_rooms", lookup_expr="lt")
    area = django_filters.NumberFilter()
    area__gt = django_filters.NumberFilter(field_name="area", lookup_expr="gt")
    area__lt = django_filters.NumberFilter(field_name="area", lookup_expr="lt")
    kitchen = django_filters.NumberFilter()
    kitchen__gt = django_filters.NumberFilter(field_name="kitchen", lookup_expr="gt")
    kitchen__lt = django_filters.NumberFilter(field_name="kitchen", lookup_expr="lt")
    features = django_filters.ModelMultipleChoiceFilter(queryset=Feature.objects.all())
    concession = django_filters.NumberFilter()
    concession__gt = django_filters.NumberFilter(field_name="concession", lookup_expr="gt")
    concession__lt = django_filters.NumberFilter(field_name="concession", lookup_expr="lt")
    deal_price = django_filters.NumberFilter()
    deal_price__gt = django_filters.NumberFilter(field_name="deal_price", lookup_expr="gt")
    deal_price__lt = django_filters.NumberFilter(field_name="deal_price", lookup_expr="lt")
    contract_price = django_filters.NumberFilter()
    contract_price__gt = django_filters.NumberFilter(field_name="contract_price", lookup_expr="gt")
    contract_price__lt = django_filters.NumberFilter(field_name="contract_price", lookup_expr="lt")
    base_price = django_filters.NumberFilter()
    base_price__gt = django_filters.NumberFilter(field_name="base_price", lookup_expr="gt")
    base_price__lt = django_filters.NumberFilter(field_name="base_price", lookup_expr="lt")
    contract_type = django_filters.ChoiceFilter(choices=Apartment.contract_types)

    class Meta:
        model = Apartment
        fields = ['id', 'commission', 'developer', 'residential_complex', 'queue', 'corpus', 'section',
                  'floor', 'floor_overall', 'deadline', 'number_of_rooms', 'area', 'kitchen', 'features',
                  'concession', 'deal_price', 'contract_price', 'base_price', 'contract_type']


class BSResidentialComplexForm(BSModalModelForm):
    class Meta:
        model = ResidentialComplex

        fields = [
            'complex_name',
            'developer'
        ]

        labels = {
            'comlex_name': 'Наименование',
            'developer': 'Застройщик'
        }

        widgets = {
            'developer': select2forms.Select2Widget()
        }


class ResidentialComplexForm(forms.ModelForm):
    developer = forms.ModelChoiceField(Developer.objects.values_list('short_name', flat=True))

    class Meta:
        model = ResidentialComplex

        fields = [
            'complex_name',
            'developer'
        ]

        widgets = {
            'complex_name': forms.TextInput(attrs={'class': 'form-control',
                                                   'id': '#residential_complex_name',
                                                   'required': True}),
        }

        labels = {
            'comlex_name': 'Наименование',
            'developer': 'Застройщик'
        }


class BSPersonForm(BSModalModelForm):
    class Meta:
        model = Person

        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'phone_number',
            'e_mail'
        ]

        labels = {
            'first_name': 'Имя',
            'middle_name': 'Отчество',
            'last_name': 'Фамилия',
            'phone_number': 'Номер телефона',
            'e_mail': 'Email'
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'id': '#person_first_name',
                                                 'required': True}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': '#person_last_name',
                                                'required': True}),
            'middle_name': forms.TextInput(attrs={'class': 'form-control',
                                                  'id': '#person_middle_name',
                                                  'required': False}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                                                   'id': '#person_phone_number',
                                                   'required': False}),
            'e_mail': forms.EmailInput(attrs={'class': 'form-control',
                                              'id': '#person_email',
                                              'required': False})
        }


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person

        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'phone_number',
            'e_mail'
        ]

        labels = {
            'first_name': 'Имя',
            'middle_name': 'Отчество',
            'last_name': 'Фамилия',
            'phone_number': 'Номер телефона',
            'e_mail': 'Email'
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'id': '#person_first_name',
                                                 'required': True}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': '#person_last_name',
                                                'required': True}),
            'middle_name': forms.TextInput(attrs={'class': 'form-control',
                                                  'id': '#person_middle_name',
                                                  'required': False}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                                                   'id': '#person_phone_number',
                                                   'required': False}),
            'e_mail': forms.EmailInput(attrs={'class': 'form-control',
                                              'id': '#person_email',
                                              'required': False})
        }


class BSBankForm(BSModalModelForm):
    class Meta:
        model = Bank

        fields = [
            'full_name',
            'short_name',
            'bik'
        ]

        labels = {
            'full_name': 'Полное наименование',
            'short_name': 'Краткое наименование',
            'bik': 'БИК'
        }

        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': "#bank_full_name",
                                                'required': False}),
            'short_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'id': '#bank_short_name',
                                                 'required': True}),
            'bik': forms.TextInput(attrs={'class': 'form-control',
                                          'id': '#bank_bik',
                                          'required': False})
        }


class BankForm(forms.ModelForm):
    class Meta:
        model = Bank

        fields = [
            'full_name',
            'short_name',
            'bik'
        ]

        labels = {
            'full_name': 'Полное наименование',
            'short_name': 'Краткое наименование',
            'bik': 'БИК'
        }

        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control',
                                                'id': "#bank_full_name",
                                                'required': False}),
            'short_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'id': '#bank_short_name',
                                                 'required': True}),

templates/references/residential_complexes/add_residential_complex.html
{% extends "base.html" %}
{% block content %}

    <div class="col-md-7 col-lg-8">

        <h3 class="mb-3 text-success">Добавление нового жилого комплекса</h3>
        <form class="post-form" action="/add_residential_complex" method="POST">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col-sm-12">
                    <label for="name" class="form-label text-success">Наименование</label>
                    {{ form.complex_name }}
                    <small id="fullNameHelp" class="form-text text-muted">Наименование жилого комплекса</small>
                </div>
                <div class="col-sm-12">
                    <label for="developer" class="form-label text-success">Застройщик</label>
                    {{ form.developer }}
                    <small id="developerHelp" class="form-text text-muted">Наименование застройщика</small>
                </div>
                <hr class="my-4">
                <button class="w-100 btn btn-success btn-lg" type="submit">Добавить жилой комплекс</button>
            </div>
        </form>
    </div>

{% endblock content %}

templates/references/residential_complexes/modal_add_residential_complex.html
<!DOCTYPE html>
<html lang="en">
<head>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <style>
        input, select {
            width: 100%
        }
    </style>

</head>
<body>
<form id="create_rc" method="post" action="/add_residential_complex">
    {% csrf_token %}

    <div class="modal-header bg-gradient bg-success"><h5 class="modal-title text-white">Новый жилой комплекс</h5></div>

    <div class="modal-body g-3 row">

        <div class="col-sm-12">
            <label for="name" class="form-label text-success">Наименование</label>
            {{ form.complex_name }}
        </div>
        <div class="col-sm-12">
            <label for="developer" class="form-label text-success">Застройщик</label>
            {{ form.developer }}
        </div>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn bg-black text-white" data-dismiss="modal">Закрыть</button>
        <button type="submit" class="btn bg-success text-white">Создать</button>
    </div>

</form>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js">
        $('#id_developer').select2({
        dropdownParent: $('#create-modal')
    });
</script>


</body>

</html>

templates/references/residential_complexes/modal_create_residential_complex.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Создать Жилой Комплекс</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-success">Создать</button>
  </div>

</form>

templates/references/residential_complexes/modal_delete_residential_complex.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Удалить Жилой Комплекс</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Вы действительно хотите удалить Жилой комплекс с наименованием
      <strong>{{ residentialcomplex.complex_name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Удалить</button>
  </div>

</form>

templates/references/residential_complexes/modal_edit_residential_complex.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Изменить Жилой Комплекс</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </div>

</form>

templates/references/residential_complexes/residential_complexes.html
{% extends "base.html" %}

{% block content %}

    <h2 class="mt-2 mb-4">Жилые Комплексы</h2>

    <div class="col-md-12">

        <button type="button" id="create_residential_complex_action"
                class="btn btn-success btn-sm"
                data-form-url="{% url 'create_rc' %}"><i class="bi-plus-circle"></i> Создать
        </button>


        <div class="table-responsive">
            <table id="residential_complexes"
                   class="display table table-light"
                   width="100%">
                <thead>

                {#                    <th><input type="checkbox" id="checkall"/></th>#}
                <th scope="col">ID</th>
                <th scope="col">Название</th>
                <th scope="col">Застройщик</th>
                <th scope="col">Создано</th>
                <th scope="col">Операции</th>

                </thead>

                <tbody>

                {% for residential_complex in residential_complexes %}
                    <tr>
                        {#                            <td><input type="checkbox" class="checkthis"/></td>#}
                        <td>{{ residential_complex.id }}</td>
                        <td>{{ residential_complex.complex_name }}</td>
                        <td> {{ residential_complex.developer.short_name }}</td>
                        <td>{{ residential_complex.created }}</td>
                        <td>
                            <button type="button"
                                    class="update_modal_action btn btn-success btn-sm"
                                    data-form-url="{% url 'edit_rc' residential_complex.pk %}"><i class="bi-pencil"></i>
                            </button>
                            <button type="button"
                                    class="delete_modal_action btn btn-dark btn-sm"
                                    data-form-url="{% url 'delete_rc' residential_complex.pk %}"><i class="bi-trash"></i>
                            </button>
                        </td>

                    </tr>
                {% endfor %}

                </tbody>

            </table>
        </div>
    </div>

{% endblock content %}